### ISSUE TITLE
No city/location is determined

### ISSUE THREAD

**Issue by thorschtn** [MelleD/ha-radar-warning#4]
Home Assistant: 2024.9.1
Radar-Warning: 0.3.2
Configuration:
   Name - Rangsdorf
   Breitengrad - 52.285828688541486
   Längengrad - 13.453831672668459
   Radius (km) - 15
   Scan intervall (minutes) - 10
   Google GeoLocation API-Schlüssel - xxxxxxxxxxxxxxxxxxxxx

Even though the Google API Key is configured, the location is not determined. street, address, address_short are filled identically to the street, no city is determined:

- id: '24730544001'
  latitude: 52.357655
  longitude: 13.587248
  street: Freiligrathstraße
  vmax: '20'
  distance: 12.109168816060599
  adress: Freiligrathstraße
  adress_short: Freiligrathstraße
  
  Nothing about it in the log file.

**Comment by MelleD** [comment]
If you get no answer then your api key is wrong or you hit a limit.

You can easily test it within your browser https://maps.googleapis.com/maps/api/geocode/json?latlng={point.latitude},{point.longitude}&key=yourkey


But yes I should log the error response.

**Comment by thorschtn** [comment]
The issue is in the README.md:

You need **Geocoding API** and not **Geolocation API**. 

You pointed me to the right direction - thanks.

**Comment by MelleD** [comment]
Yes you are right it’s the Geocoding API.
But then 2 issues and 1 FR
A) log error response 
B) fix readme

FR
C) attribute for city
